let shopItemsData = [
  {
    id: "jfhgbvnscs",
    name: "მაისური",
    price: 35,
    desc: "წითელი მაისური - Puma",
    img: "images/product-1.jpg",
  },
  {
    id: "ioytrhndcv",
    name: "სპორტული ფეხსაცმელი",
    price: 50,
    desc: "შავი ფეხსაცმელი HRX",
    img: "images/product-2.jpg",
  },
  {
    id: "wuefbncxbsn",
    name: "სპორტული შარვალი",
    price: 45,
    desc: "ნაცრისფერი შარვალი",
    img: "images/product-3.jpg",
  },
  {
    id: "thyfhcbcv",
    name: "მაისური",
    price: 30,
    desc: "ლურჯი მაისური - Puma",
    img: "images/product-4.jpg",
  },
  {
    id: "thiecbawdjksadjk",
    name: "სპორტული ფეხსაცმელი",
    price: 70,
    desc: "ნაცრისფერი მაღალყელიანი ფეხსაცმელი თეთრი ძირით",
    img: "images/product-5.jpg",
  },
  {
    id: "iuertrywebncdjksadjk",
    name: "მაისური",
    price: 35,
    desc: "ზოლებიანი შავი მაისური - Puma",
    img: "images/product-6.jpg",
  },
  {
    id: "thierytbvcbvzdhadjk",
    name: "წინდები",
    price: 30,
    desc: "წინდების კომპლექტი - შავი+თეთრი+ნაცრისფერი",
    img: "images/product-7.jpg",
  },
  {
    id: "trfoiwfcnbcawdjksadjk",
    name: "მაჯის საათი",
    price: 120,
    desc: "შავი - Fossil",
    img: "images/product-8.jpg",
  },
  {
    id: "cbvxbcvsceldk",
    name: "მაჯის საათი",
    price: 110,
    desc: "ნაცრისფერი",
    img: "images/product-9.jpg",
  },
  {
    id: "oiopijmjkhuihb",
    name: "სპორტული ფეხსაცმელი",
    price: 120,
    desc: "შავი+ნავცრისფერი+წითელი - HRX",
    img: "images/product-10.jpg",
  },
  {
    id: "oiopijewyiohbjhib",
    name: "სპორტული ფეხსაცმელი",
    price: 45,
    desc: "ნაცრისფერი ფეხსაცმელი თეთრი ძირით",
    img: "images/product-11.jpg",
  },
  {
    id: "jhgjgjgjgjgkjhkjhkjh",
    name: "სპორტული შარვალი",
    price: 80,
    desc: "შავი შარვალი - Nike",
    img: "images/product-12.jpg",
  },
  {
    id: "ljljkjlkjljljljlj",
    name: "სმარტ სამაჯური",
    price: 350,
    desc: "სმარტ სამაჯური მი-4",
    img: "images/exclusive.png",
  },
];
